TMP-commit, squash later (2025-05-01T22:12:49)

diff --git a/.github/workflows/mirror_private_to_public.yaml b/.github/workflows/mirror_private_to_public.yaml
--- a/.github/workflows/mirror_private_to_public.yaml
+++ b/.github/workflows/mirror_private_to_public.yaml
@@ -21,7 +21,9 @@ jobs:
       - name: Authenticate GitHub CLI
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: gh auth login --with-token <<< "${GH_TOKEN}"
+        run: |
+          gh auth login --with-token <<< "${GH_TOKEN}" ||
+          { echo "GitHub CLI authentication failed!"; exit 1; }
 
       - name: Provide Script
         run: |
