TMP-commit, squash later (2025-05-02T00:49:32)

diff --git a/.github/workflows/mirror_private_to_public.yaml b/.github/workflows/mirror_private_to_public.yaml
--- a/.github/workflows/mirror_private_to_public.yaml
+++ b/.github/workflows/mirror_private_to_public.yaml
@@ -19,19 +19,18 @@ jobs:
 
       - name: Authenticate GitHub CLI
         env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GH_TOKEN: ${{ secrets.GH_PAT }}
+        # ENIGMA How to solve the authentication problem
         run: |
           echo "${GH_TOKEN}" | 
           gh auth login --with-token || 
-          { echo "GitHub CLIzz authentication failed!"; exit 1; }
+          { echo "GitHub CLI authentication failed!"; exit 1; }
 
-      # - name: Provide Script
-      #   run: |
-      #     mkdir -p ./scripts
-      #     curl -o ./scripts/mirror_private_to_public.sh https://raw.githubusercontent.com/kvn-dtrx/git-hub-automatisation/main/scripts/mirror_private_to_public.sh
-      #     chmod +x ./scripts/mirror_private_to_public.sh
+      - name: Provide Script
+        run: |
+          mkdir -p ./scripts
+          curl -o ./scripts/mirror_private_to_public.sh https://raw.githubusercontent.com/kvn-dtrx/git-hub-automatisation/main/scripts/mirror_private_to_public.sh
+          chmod +x ./scripts/mirror_private_to_public.sh
 
-      # - name: Mirror Private to Public
-      #   run: ./scripts/mirror_private_to_public.sh
-      #   # env:
-      #   #   GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
+      - name: Mirror Private to Public
+        run: ./scripts/mirror_private_to_public.sh
